# Variables
vm_node = 5
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure("2") do |config|
    
    config.timezone.value = :host
    config.vm.box_check_update = false
    config.vm.box = "generic/debian12"
    config.vm.provision "shell", path: "bootstrap.sh"

    (1..vm_node).each do |i|
        config.vm.define "cka-#{i}" do |node|
            node.vm.provider "libvirt" do |vb|
                vb.memory = 4 * 1024
                vb.cpus = 4
            end
            node.vm.hostname = "cka-#{i}"
        end
    end
end
