---
- name: VM Provisoning
  hosts: all
  tasks:
  
  - name: Install Basic Packages
    become: yes
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - screen
      - wget
      - curl
      - telnet
      - net-tools
      - java-1.8.0-openjdk-devel

  - name: Add all hosts to /etc/hosts # using nat bridgr here
    become: yes
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"
      
      