---
- name: VM Provisoning
  become: true
  hosts: all
  tasks:

  - name: Install Basic Packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - screen
      - wget
      - curl
      - telnet
      - net-tools
      - vim
      - ntp*
      - unzip
      - java-1.8.0-openjdk-devel

  - name: Disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no

  - name: Set timezone to Asia/Dhaka
    timezone:
      name: Asia/Dhaka

  - name: Enable ntp
    systemd:
      name: ntpd
      state: started
      enabled: yes


  - name: Add all hosts to /etc/hosts
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"


