# Variables
vm_node = 3
net = "192.168.56."
vm_node_start = 110
vm_gateway = "192.168.56.1"

Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.vm.box = "centos/7"
    config.vm.provision "add vms to /etc/hosts", type: "shell", privileged: true,
        inline: "
    echo '
    192.168.56.111 vm-1
    192.168.56.112 vm-2
    192.168.56.113 vm-3
    192.168.56.114 vm-4
    192.168.56.115 vm-5
    192.168.56.116 vm-6' >> /etc/hosts
    "
    config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
    end
    
    (1..vm_node).each do |i|
        config.vm.define "vm-#{i}" do |node|
        #config.vm.network "public_network" 
            node.vm.provider "libvirt" do |vb|
                vb.memory = 2048
                vb.cpus = 2            
            end
            node.vm.hostname = "vm-#{i}"
            node.vm.network :private_network, ip: net + "#{vm_node_start + i}", gateway: vm_gateway
        end
    end
end
