# Variables
vm_node = 1
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
end

Vagrant.configure("2") do |config|
    config.vm.box_check_update = false

    config.vm.box = "generic/ubuntu2204"
    config.vm.provision "shell", path: "bootstrap.sh"

    (1..vm_node).each do |i|
        config.vm.define "vm-#{i}" do |node|
        #config.vm.network "public_network"
            node.vm.provider "libvirt" do |vb|
                vb.memory = 4096
                vb.cpus = 4
            end
            node.vm.hostname = "ubuntu2004-#{i}"
        end
    end
end
