# Variables
vm_node = 1

Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    
    config.vm.box = "generic/ubuntu1804"
    
    (1..vm_node).each do |i|
        config.vm.define "ubuntu-#{i}" do |node|
        #config.vm.network "public_network" 
            node.vm.provider "libvirt" do |vb|
                vb.memory = 4096
                vb.cpus = 4            
            end
            node.vm.hostname = "ubuntu-#{i}"
        end
    end
end
