ENV['VAGRANT_NO_PARALLEL'] = 'yes'

# Number of vms I need
vm_node = 1

if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
end

Vagrant.configure("2") do |config|

    config.vm.box_check_update = false
    config.vm.box = "generic/rocky9"
    config.vm.provision "shell", path: "bootstrap.sh"

    (1..vm_node).each do |i|
        config.vm.define "vm-#{i}" do |node|
            node.vm.provider "libvirt" do |vb|
                vb.memory = 2048
                vb.cpus = 2
            
            end
            node.vm.hostname = "rocky9-#{i}"
        end
    end
end
