# Number of vms I need
vm_node = 3

Vagrant.configure("2") do |config|
    config.vm.box_check_update = false
    config.vm.box = "generic/centos8"

    #config.vm.provision "ansible" do |ansible|
    #    ansible.playbook = "playbook.yml"
    #end

    (1..vm_node).each do |i|
        config.vm.define "vm-#{i}" do |node|
            node.vm.provider "libvirt" do |vb|
                vb.memory = 4096
                vb.cpus = 4
            end
            node.vm.hostname = "vm-#{i}"
        end
    end
end
