ENV['VAGRANT_NO_PARALLEL'] = 'yes'

# Variables
vm_node = 1

if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
end

Vagrant.configure("2") do |config|
    config.vm.box_check_update = false

    config.vm.box = "generic/debian11"
    config.vm.provision "shell", path: "bootstrap.sh"

    (1..vm_node).each do |i|
        config.vm.define "vm-#{i}" do |node|
            node.vm.provider "libvirt" do |vb|
                vb.memory = 4048
                vb.cpus = 4
            end
            node.vm.hostname = "debian11-#{i}"
        end
    end
end
