---
- name: VM Provisoning
  gather_facts: no
  become: yes
  hosts: all
  tasks:

  - name: Install Basic Packages
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - screen
      - wget
      - curl
      - telnet
      - net-tools
      - ntp
      - java-1.8.0-openjdk-devel
      - epel-release

  - name: Disable firewalld
    systemd:
      name: firewalld
      state: stopped
      enabled: no
      masked: yes

  - name: Enable ntp
    systemd:
      name: ntpd
      state: started
      enabled: yes


  - name: Add all hosts to /etc/hosts # using nat bridgr here
    lineinfile:
      dest: /etc/hosts
      regexp: '.*{{ item }}$'
      line: "{{ hostvars[item].ansible_host }} {{item}}"
      state: present
    when: hostvars[item].ansible_host is defined
    with_items: "{{ groups.all }}"


